export enum CameraTypes {
  DEFAULT_ANIMATED_CAMERA = "DEFAULT_ANIMATED_CAMERA",
  DEFAULT_SCRIPTED_CAMERA = "DEFAULT_SCRIPTED_CAMERA",
  DEFAULT_SCRIPTED_FLY_CAMERA = "DEFAULT_SCRIPTED_FLY_CAMERA",
  DEFAULT_SPLINE_CAMERA = "DEFAULT_SPLINE_CAMERA",
}
